# Generated by Django 4.2.19 on 2025-08-19 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedicatedaccount',
            name='dadicated_account_user',
        ),
        migrations.AddField(
            model_name='dedicatedaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_account_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
