# Generated by Django 4.2.19 on 2025-08-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_dedicatedaccount_dadicated_account_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dedicatedaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
