# Generated by Django 5.1.6 on 2025-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleinvite',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
