# Generated by Django 4.2 on 2025-04-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
