# Generated by Django 4.2 on 2025-03-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_id',
        ),
    ]
