# Generated by Django 4.2 on 2025-04-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='submitted_at',
        ),
    ]
