# Generated by Django 4.2 on 2025-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_card_holder_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_holder_ref',
            new_name='card_holder_ref_id',
        ),
        migrations.AddField(
            model_name='card',
            name='card_ref_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
