# Generated by Django 5.1.6 on 2025-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bankdetails_transactions_userprofile_bvn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
