# Generated by Django 4.2 on 2025-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_kycverification_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
