# Generated by Django 4.2 on 2025-03-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userprofile_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
