# Generated by Django 4.2 on 2025-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
