# Generated by Django 4.2 on 2025-05-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wallet_usd_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='eur_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
