# Generated by Django 4.2 on 2025-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_otp_security_otp_transaction_otp_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vt_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
