# Generated by Django 4.2 on 2025-04-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kycverification_submitted_at'),
        ('main', '0003_otp_security_otp_transaction_otp_userprofile_otp'),
    ]

    operations = [
    ]
