# Generated by Django 4.2 on 2025-03-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_card_holder_ref_card_card_holder_ref_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
