# Generated by Django 4.2 on 2025-03-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_referral_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='security',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
