# Generated by Django 5.1.6 on 2025-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_roleinvite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinvite',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
