# Generated by Django 5.1.6 on 2025-03-02 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_wallet_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
