# Generated by Django 4.2.19 on 2025-05-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wallet_eur_balance'),
        ('main', '0004_merge_20250411_0006'),
    ]

    operations = [
    ]
