# Generated by Django 4.2 on 2025-03-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_card_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
