# Generated by Django 4.2 on 2025-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_otp_options_alter_security_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
