# Generated by Django 4.2 on 2025-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_transaction_vt_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('processing', 'processing'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
