# Generated by Django 4.2 on 2025-05-14 19:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20250511_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default=main.models.generate_unique_identifier, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('processing', 'processing'), ('refunded', 'refunded'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
