# Generated by Django 4.2 on 2025-03-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_card_card_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_four',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
