# Generated by Django 4.2 on 2025-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_otp_expiry_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_duration',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
