# Generated by Django 5.1.6 on 2025-03-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_business_transaction_delete_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
