# Generated by Django 4.2 on 2025-05-14 19:49

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_transaction_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default=main.models.generate_unique_identifier, editable=False, max_length=100, unique=True),
        ),
    ]
