# Generated by Django 5.1.6 on 2025-03-04 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_businessterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='card_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=200, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=10, null=True)),
                ('card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
