# Generated by Django 4.2 on 2025-05-15 21:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default=main.models.generate_unique_identifier, max_length=100, unique=True),
        ),
    ]
