# Generated by Django 4.2 on 2025-06-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('debit', 'debit'), ('credit', 'credit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed'), ('processing', 'processing'), ('refunded', 'refunded'), ('failed', 'failed')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('transfer', 'transfer'), ('subscription', 'subscription')], max_length=20, null=True),
        ),
    ]
