# Generated by Django 4.2 on 2025-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_data',
            field=models.JSONField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('transfer', 'transfer'), ('subscription', 'subscription')], max_length=20),
        ),
    ]
