# Generated by Django 4.2 on 2025-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_transaction_paystack_data_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='funds',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
