# Generated by Django 4.2.19 on 2025-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_transaction_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed'), ('processing', 'processing'), ('refunded', 'refunded'), ('failed', 'Failed')], default='pending', max_length=10, null=True),
        ),
    ]
