# Generated by Django 4.2.19 on 2025-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='raw_response',
            field=models.JSONField(blank=True, max_length=999999, null=True),
        ),
    ]
