# Generated by Django 4.2 on 2025-04-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
    ]
