# Generated by Django 4.2 on 2025-04-01 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
