# Generated by Django 4.2 on 2025-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expiry_duration',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
