# Generated by Django 4.2 on 2025-04-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='otp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.otp'),
        ),
    ]
