# Generated by Django 4.2 on 2025-04-01 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_security_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='otp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tx_otp', to='main.otp'),
        ),
        migrations.AlterField(
            model_name='security',
            name='otp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_otp', to='main.otp'),
        ),
    ]
