# Generated by Django 4.2 on 2025-04-04 22:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_userprofile_otp_alter_security_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='userimg_cgc9gs.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
