# Generated by Django 4.2 on 2025-04-04 23:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_kycverification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_document'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='selfie',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='selfie'),
        ),
    ]
