# Generated by Django 5.1.6 on 2025-02-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin1', 'admin1'), ('admin', 'admin'), ('staff', 'staff'), ('merchant', 'merchant'), ('user', 'user')], max_length=100, null=True),
        ),
    ]
