# Generated by Django 5.1.6 on 2025-02-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='security',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
