# Generated by Django 5.1.6 on 2025-02-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_security_date_created_alter_security_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='selfie',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
