# Generated by Django 5.1.6 on 2025-02-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_kycverification_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_document',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
