# Generated by Django 5.1.6 on 2025-02-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_kycverification_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin1', 'admin1'), ('admin', 'admin'), ('staff', 'staff'), ('merchant', 'merchant'), ('user', 'user')], default='user', max_length=100, null=True),
        ),
    ]
