# Generated by Django 5.1.6 on 2025-03-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_kycverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
