# Generated by Django 5.1.6 on 2025-03-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_kycverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='reviewed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 7, 39, 52, 537248, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 7, 39, 52, 537248, tzinfo=datetime.timezone.utc)),
        ),
    ]
