# Generated by Django 5.1.6 on 2025-03-01 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_alter_kycverification_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
