# Generated by Django 5.1.6 on 2025-03-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_alter_kycverification_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
