# Generated by Django 5.1.6 on 2025-03-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_alter_kycverification_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
